apiVersion: v1
kind: LimitRange
metadata:
  name: storage-limit-range
spec:
  limits:
  - default:
      ephemeral-storage: "2Gi"
    type: Container

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mctech-order
  labels:
    app: mctech-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mctech-order
  template:
    metadata:
      labels:
        app: mctech-order
    spec:
      containers:
        - name: mctech-order-container
          image: ghcr.io/grupo-68-fiap/mctech/order:latest # NOSONAR
          env:
            - name: REDIS_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: mctech-order-secret
                  key: CONNECTION_STRING 
            - name: OPENID_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: cognito-secrets
                  key: OPENID_AUTHORITY
            - name: OPENID_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: cognito-secrets
                  key: OPENID_AUDIENCE
          envFrom:
            - configMapRef:
                name: mctech-order-configmap
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /swagger
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /swagger
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 30
          resources:
            requests:
              memory: 64Mi
              cpu: 5m
              ephemeral-storage: "1Gi"
            limits:
              memory: 256Mi
              cpu: 200m
              ephemeral-storage: "2Gi"
      automountServiceAccountToken: false
